import type { Metadata } from 'next'
import { Nunito } from 'next/font/google'
import '@/styles/globals.css'

const font = Nunito({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: {
    default: 'GH SEARCH',
    template: '%S | GH SEARCH',
  },
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${font.className} animated-gradient-bg w-screen text-slate-50`}>
        <div className="mx-auto w-full max-w-[1200px]">{children}</div>
      </body>
    </html>
  )
}
